version: "3.0"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
